// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package jadex.android.bluetooth.message;

public final class MessageProtos {
  private MessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public enum RoutingType
      implements com.google.protobuf.Internal.EnumLite {
    Flooding(0, 1),
    DSDV(1, 2),
    DSR(2, 3),
    ;
    
    public static final int Flooding_VALUE = 1;
    public static final int DSDV_VALUE = 2;
    public static final int DSR_VALUE = 3;
    
    
    public final int getNumber() { return value; }
    
    public static RoutingType valueOf(int value) {
      switch (value) {
        case 1: return Flooding;
        case 2: return DSDV;
        case 3: return DSR;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<RoutingType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<RoutingType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RoutingType>() {
            public RoutingType findValueByNumber(int number) {
              return RoutingType.valueOf(number);
            }
          };
    
    private final int value;
    
    private RoutingType(int index, int value) {
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:jadex.android.bluetooth.message.RoutingType)
  }
  
  public interface RoutingTableOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // repeated .jadex.android.bluetooth.message.RoutingTableEntry entry = 1;
    java.util.List<jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry> 
        getEntryList();
    jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry getEntry(int index);
    int getEntryCount();
  }
  public static final class RoutingTable extends
      com.google.protobuf.GeneratedMessageLite
      implements RoutingTableOrBuilder {
    // Use RoutingTable.newBuilder() to construct.
    private RoutingTable(Builder builder) {
      super(builder);
    }
    private RoutingTable(boolean noInit) {}
    
    private static final RoutingTable defaultInstance;
    public static RoutingTable getDefaultInstance() {
      return defaultInstance;
    }
    
    public RoutingTable getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // repeated .jadex.android.bluetooth.message.RoutingTableEntry entry = 1;
    public static final int ENTRY_FIELD_NUMBER = 1;
    private java.util.List<jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry> entry_;
    public java.util.List<jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry> getEntryList() {
      return entry_;
    }
    public java.util.List<? extends jadex.android.bluetooth.message.MessageProtos.RoutingTableEntryOrBuilder> 
        getEntryOrBuilderList() {
      return entry_;
    }
    public int getEntryCount() {
      return entry_.size();
    }
    public jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry getEntry(int index) {
      return entry_.get(index);
    }
    public jadex.android.bluetooth.message.MessageProtos.RoutingTableEntryOrBuilder getEntryOrBuilder(
        int index) {
      return entry_.get(index);
    }
    
    private void initFields() {
      entry_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getEntryCount(); i++) {
        if (!getEntry(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < entry_.size(); i++) {
        output.writeMessage(1, entry_.get(i));
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < entry_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, entry_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static jadex.android.bluetooth.message.MessageProtos.RoutingTable parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static jadex.android.bluetooth.message.MessageProtos.RoutingTable parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static jadex.android.bluetooth.message.MessageProtos.RoutingTable parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static jadex.android.bluetooth.message.MessageProtos.RoutingTable parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static jadex.android.bluetooth.message.MessageProtos.RoutingTable parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static jadex.android.bluetooth.message.MessageProtos.RoutingTable parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static jadex.android.bluetooth.message.MessageProtos.RoutingTable parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static jadex.android.bluetooth.message.MessageProtos.RoutingTable parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static jadex.android.bluetooth.message.MessageProtos.RoutingTable parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static jadex.android.bluetooth.message.MessageProtos.RoutingTable parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(jadex.android.bluetooth.message.MessageProtos.RoutingTable prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          jadex.android.bluetooth.message.MessageProtos.RoutingTable, Builder>
        implements jadex.android.bluetooth.message.MessageProtos.RoutingTableOrBuilder {
      // Construct using jadex.android.bluetooth.message.MessageProtos.RoutingTable.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        entry_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public jadex.android.bluetooth.message.MessageProtos.RoutingTable getDefaultInstanceForType() {
        return jadex.android.bluetooth.message.MessageProtos.RoutingTable.getDefaultInstance();
      }
      
      public jadex.android.bluetooth.message.MessageProtos.RoutingTable build() {
        jadex.android.bluetooth.message.MessageProtos.RoutingTable result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private jadex.android.bluetooth.message.MessageProtos.RoutingTable buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        jadex.android.bluetooth.message.MessageProtos.RoutingTable result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public jadex.android.bluetooth.message.MessageProtos.RoutingTable buildPartial() {
        jadex.android.bluetooth.message.MessageProtos.RoutingTable result = new jadex.android.bluetooth.message.MessageProtos.RoutingTable(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          entry_ = java.util.Collections.unmodifiableList(entry_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.entry_ = entry_;
        return result;
      }
      
      public Builder mergeFrom(jadex.android.bluetooth.message.MessageProtos.RoutingTable other) {
        if (other == jadex.android.bluetooth.message.MessageProtos.RoutingTable.getDefaultInstance()) return this;
        if (!other.entry_.isEmpty()) {
          if (entry_.isEmpty()) {
            entry_ = other.entry_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEntryIsMutable();
            entry_.addAll(other.entry_);
          }
          
        }
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getEntryCount(); i++) {
          if (!getEntry(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry.Builder subBuilder = jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addEntry(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .jadex.android.bluetooth.message.RoutingTableEntry entry = 1;
      private java.util.List<jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry> entry_ =
        java.util.Collections.emptyList();
      private void ensureEntryIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          entry_ = new java.util.ArrayList<jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry>(entry_);
          bitField0_ |= 0x00000001;
         }
      }
      
      public java.util.List<jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry> getEntryList() {
        return java.util.Collections.unmodifiableList(entry_);
      }
      public int getEntryCount() {
        return entry_.size();
      }
      public jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry getEntry(int index) {
        return entry_.get(index);
      }
      public Builder setEntry(
          int index, jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntryIsMutable();
        entry_.set(index, value);
        
        return this;
      }
      public Builder setEntry(
          int index, jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry.Builder builderForValue) {
        ensureEntryIsMutable();
        entry_.set(index, builderForValue.build());
        
        return this;
      }
      public Builder addEntry(jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntryIsMutable();
        entry_.add(value);
        
        return this;
      }
      public Builder addEntry(
          int index, jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntryIsMutable();
        entry_.add(index, value);
        
        return this;
      }
      public Builder addEntry(
          jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry.Builder builderForValue) {
        ensureEntryIsMutable();
        entry_.add(builderForValue.build());
        
        return this;
      }
      public Builder addEntry(
          int index, jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry.Builder builderForValue) {
        ensureEntryIsMutable();
        entry_.add(index, builderForValue.build());
        
        return this;
      }
      public Builder addAllEntry(
          java.lang.Iterable<? extends jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry> values) {
        ensureEntryIsMutable();
        super.addAll(values, entry_);
        
        return this;
      }
      public Builder clearEntry() {
        entry_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        
        return this;
      }
      public Builder removeEntry(int index) {
        ensureEntryIsMutable();
        entry_.remove(index);
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:jadex.android.bluetooth.message.RoutingTable)
    }
    
    static {
      defaultInstance = new RoutingTable(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:jadex.android.bluetooth.message.RoutingTable)
  }
  
  public interface RoutingTableEntryOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required string destination = 1;
    boolean hasDestination();
    String getDestination();
    
    // optional string nextHop = 2;
    boolean hasNextHop();
    String getNextHop();
    
    // optional int32 numHops = 3 [default = 0];
    boolean hasNumHops();
    int getNumHops();
    
    // optional int32 seqNum = 4;
    boolean hasSeqNum();
    int getSeqNum();
    
    // optional int64 routeCreationTime = 5;
    boolean hasRouteCreationTime();
    long getRouteCreationTime();
    
    // optional bool routeChanged = 6 [default = false];
    boolean hasRouteChanged();
    boolean getRouteChanged();
  }
  public static final class RoutingTableEntry extends
      com.google.protobuf.GeneratedMessageLite
      implements RoutingTableEntryOrBuilder {
    // Use RoutingTableEntry.newBuilder() to construct.
    private RoutingTableEntry(Builder builder) {
      super(builder);
    }
    private RoutingTableEntry(boolean noInit) {}
    
    private static final RoutingTableEntry defaultInstance;
    public static RoutingTableEntry getDefaultInstance() {
      return defaultInstance;
    }
    
    public RoutingTableEntry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required string destination = 1;
    public static final int DESTINATION_FIELD_NUMBER = 1;
    private java.lang.Object destination_;
    public boolean hasDestination() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getDestination() {
      java.lang.Object ref = destination_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          destination_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDestinationBytes() {
      java.lang.Object ref = destination_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        destination_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string nextHop = 2;
    public static final int NEXTHOP_FIELD_NUMBER = 2;
    private java.lang.Object nextHop_;
    public boolean hasNextHop() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getNextHop() {
      java.lang.Object ref = nextHop_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          nextHop_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNextHopBytes() {
      java.lang.Object ref = nextHop_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        nextHop_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 numHops = 3 [default = 0];
    public static final int NUMHOPS_FIELD_NUMBER = 3;
    private int numHops_;
    public boolean hasNumHops() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getNumHops() {
      return numHops_;
    }
    
    // optional int32 seqNum = 4;
    public static final int SEQNUM_FIELD_NUMBER = 4;
    private int seqNum_;
    public boolean hasSeqNum() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getSeqNum() {
      return seqNum_;
    }
    
    // optional int64 routeCreationTime = 5;
    public static final int ROUTECREATIONTIME_FIELD_NUMBER = 5;
    private long routeCreationTime_;
    public boolean hasRouteCreationTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public long getRouteCreationTime() {
      return routeCreationTime_;
    }
    
    // optional bool routeChanged = 6 [default = false];
    public static final int ROUTECHANGED_FIELD_NUMBER = 6;
    private boolean routeChanged_;
    public boolean hasRouteChanged() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public boolean getRouteChanged() {
      return routeChanged_;
    }
    
    private void initFields() {
      destination_ = "";
      nextHop_ = "";
      numHops_ = 0;
      seqNum_ = 0;
      routeCreationTime_ = 0L;
      routeChanged_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasDestination()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDestinationBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNextHopBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, numHops_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, seqNum_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, routeCreationTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, routeChanged_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDestinationBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNextHopBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, numHops_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, seqNum_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, routeCreationTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, routeChanged_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry, Builder>
        implements jadex.android.bluetooth.message.MessageProtos.RoutingTableEntryOrBuilder {
      // Construct using jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        destination_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        nextHop_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        numHops_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        seqNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        routeCreationTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        routeChanged_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry getDefaultInstanceForType() {
        return jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry.getDefaultInstance();
      }
      
      public jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry build() {
        jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry buildPartial() {
        jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry result = new jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.destination_ = destination_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nextHop_ = nextHop_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.numHops_ = numHops_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.seqNum_ = seqNum_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.routeCreationTime_ = routeCreationTime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.routeChanged_ = routeChanged_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry other) {
        if (other == jadex.android.bluetooth.message.MessageProtos.RoutingTableEntry.getDefaultInstance()) return this;
        if (other.hasDestination()) {
          setDestination(other.getDestination());
        }
        if (other.hasNextHop()) {
          setNextHop(other.getNextHop());
        }
        if (other.hasNumHops()) {
          setNumHops(other.getNumHops());
        }
        if (other.hasSeqNum()) {
          setSeqNum(other.getSeqNum());
        }
        if (other.hasRouteCreationTime()) {
          setRouteCreationTime(other.getRouteCreationTime());
        }
        if (other.hasRouteChanged()) {
          setRouteChanged(other.getRouteChanged());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasDestination()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              destination_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              nextHop_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              numHops_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              seqNum_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              routeCreationTime_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              routeChanged_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string destination = 1;
      private java.lang.Object destination_ = "";
      public boolean hasDestination() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getDestination() {
        java.lang.Object ref = destination_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          destination_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDestination(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        destination_ = value;
        
        return this;
      }
      public Builder clearDestination() {
        bitField0_ = (bitField0_ & ~0x00000001);
        destination_ = getDefaultInstance().getDestination();
        
        return this;
      }
      void setDestination(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        destination_ = value;
        
      }
      
      // optional string nextHop = 2;
      private java.lang.Object nextHop_ = "";
      public boolean hasNextHop() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getNextHop() {
        java.lang.Object ref = nextHop_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          nextHop_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNextHop(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nextHop_ = value;
        
        return this;
      }
      public Builder clearNextHop() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nextHop_ = getDefaultInstance().getNextHop();
        
        return this;
      }
      void setNextHop(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        nextHop_ = value;
        
      }
      
      // optional int32 numHops = 3 [default = 0];
      private int numHops_ ;
      public boolean hasNumHops() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getNumHops() {
        return numHops_;
      }
      public Builder setNumHops(int value) {
        bitField0_ |= 0x00000004;
        numHops_ = value;
        
        return this;
      }
      public Builder clearNumHops() {
        bitField0_ = (bitField0_ & ~0x00000004);
        numHops_ = 0;
        
        return this;
      }
      
      // optional int32 seqNum = 4;
      private int seqNum_ ;
      public boolean hasSeqNum() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getSeqNum() {
        return seqNum_;
      }
      public Builder setSeqNum(int value) {
        bitField0_ |= 0x00000008;
        seqNum_ = value;
        
        return this;
      }
      public Builder clearSeqNum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        seqNum_ = 0;
        
        return this;
      }
      
      // optional int64 routeCreationTime = 5;
      private long routeCreationTime_ ;
      public boolean hasRouteCreationTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public long getRouteCreationTime() {
        return routeCreationTime_;
      }
      public Builder setRouteCreationTime(long value) {
        bitField0_ |= 0x00000010;
        routeCreationTime_ = value;
        
        return this;
      }
      public Builder clearRouteCreationTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        routeCreationTime_ = 0L;
        
        return this;
      }
      
      // optional bool routeChanged = 6 [default = false];
      private boolean routeChanged_ ;
      public boolean hasRouteChanged() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public boolean getRouteChanged() {
        return routeChanged_;
      }
      public Builder setRouteChanged(boolean value) {
        bitField0_ |= 0x00000020;
        routeChanged_ = value;
        
        return this;
      }
      public Builder clearRouteChanged() {
        bitField0_ = (bitField0_ & ~0x00000020);
        routeChanged_ = false;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:jadex.android.bluetooth.message.RoutingTableEntry)
    }
    
    static {
      defaultInstance = new RoutingTableEntry(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:jadex.android.bluetooth.message.RoutingTableEntry)
  }
  
  public interface RoutingInformationOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required .jadex.android.bluetooth.message.RoutingType type = 1;
    boolean hasType();
    jadex.android.bluetooth.message.MessageProtos.RoutingType getType();
    
    // optional string fromAddress = 2;
    boolean hasFromAddress();
    String getFromAddress();
    
    // required .jadex.android.bluetooth.message.RoutingTable routingTable = 3;
    boolean hasRoutingTable();
    jadex.android.bluetooth.message.MessageProtos.RoutingTable getRoutingTable();
    
    // optional bool routeDownInformation = 4 [default = false];
    boolean hasRouteDownInformation();
    boolean getRouteDownInformation();
  }
  public static final class RoutingInformation extends
      com.google.protobuf.GeneratedMessageLite
      implements RoutingInformationOrBuilder {
    // Use RoutingInformation.newBuilder() to construct.
    private RoutingInformation(Builder builder) {
      super(builder);
    }
    private RoutingInformation(boolean noInit) {}
    
    private static final RoutingInformation defaultInstance;
    public static RoutingInformation getDefaultInstance() {
      return defaultInstance;
    }
    
    public RoutingInformation getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required .jadex.android.bluetooth.message.RoutingType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private jadex.android.bluetooth.message.MessageProtos.RoutingType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public jadex.android.bluetooth.message.MessageProtos.RoutingType getType() {
      return type_;
    }
    
    // optional string fromAddress = 2;
    public static final int FROMADDRESS_FIELD_NUMBER = 2;
    private java.lang.Object fromAddress_;
    public boolean hasFromAddress() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getFromAddress() {
      java.lang.Object ref = fromAddress_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          fromAddress_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFromAddressBytes() {
      java.lang.Object ref = fromAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        fromAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .jadex.android.bluetooth.message.RoutingTable routingTable = 3;
    public static final int ROUTINGTABLE_FIELD_NUMBER = 3;
    private jadex.android.bluetooth.message.MessageProtos.RoutingTable routingTable_;
    public boolean hasRoutingTable() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public jadex.android.bluetooth.message.MessageProtos.RoutingTable getRoutingTable() {
      return routingTable_;
    }
    
    // optional bool routeDownInformation = 4 [default = false];
    public static final int ROUTEDOWNINFORMATION_FIELD_NUMBER = 4;
    private boolean routeDownInformation_;
    public boolean hasRouteDownInformation() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public boolean getRouteDownInformation() {
      return routeDownInformation_;
    }
    
    private void initFields() {
      type_ = jadex.android.bluetooth.message.MessageProtos.RoutingType.Flooding;
      fromAddress_ = "";
      routingTable_ = jadex.android.bluetooth.message.MessageProtos.RoutingTable.getDefaultInstance();
      routeDownInformation_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRoutingTable()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getRoutingTable().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFromAddressBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, routingTable_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, routeDownInformation_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFromAddressBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, routingTable_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, routeDownInformation_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static jadex.android.bluetooth.message.MessageProtos.RoutingInformation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static jadex.android.bluetooth.message.MessageProtos.RoutingInformation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static jadex.android.bluetooth.message.MessageProtos.RoutingInformation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static jadex.android.bluetooth.message.MessageProtos.RoutingInformation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static jadex.android.bluetooth.message.MessageProtos.RoutingInformation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static jadex.android.bluetooth.message.MessageProtos.RoutingInformation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static jadex.android.bluetooth.message.MessageProtos.RoutingInformation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static jadex.android.bluetooth.message.MessageProtos.RoutingInformation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static jadex.android.bluetooth.message.MessageProtos.RoutingInformation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static jadex.android.bluetooth.message.MessageProtos.RoutingInformation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(jadex.android.bluetooth.message.MessageProtos.RoutingInformation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          jadex.android.bluetooth.message.MessageProtos.RoutingInformation, Builder>
        implements jadex.android.bluetooth.message.MessageProtos.RoutingInformationOrBuilder {
      // Construct using jadex.android.bluetooth.message.MessageProtos.RoutingInformation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = jadex.android.bluetooth.message.MessageProtos.RoutingType.Flooding;
        bitField0_ = (bitField0_ & ~0x00000001);
        fromAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        routingTable_ = jadex.android.bluetooth.message.MessageProtos.RoutingTable.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000004);
        routeDownInformation_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public jadex.android.bluetooth.message.MessageProtos.RoutingInformation getDefaultInstanceForType() {
        return jadex.android.bluetooth.message.MessageProtos.RoutingInformation.getDefaultInstance();
      }
      
      public jadex.android.bluetooth.message.MessageProtos.RoutingInformation build() {
        jadex.android.bluetooth.message.MessageProtos.RoutingInformation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private jadex.android.bluetooth.message.MessageProtos.RoutingInformation buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        jadex.android.bluetooth.message.MessageProtos.RoutingInformation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public jadex.android.bluetooth.message.MessageProtos.RoutingInformation buildPartial() {
        jadex.android.bluetooth.message.MessageProtos.RoutingInformation result = new jadex.android.bluetooth.message.MessageProtos.RoutingInformation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fromAddress_ = fromAddress_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.routingTable_ = routingTable_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.routeDownInformation_ = routeDownInformation_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(jadex.android.bluetooth.message.MessageProtos.RoutingInformation other) {
        if (other == jadex.android.bluetooth.message.MessageProtos.RoutingInformation.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasFromAddress()) {
          setFromAddress(other.getFromAddress());
        }
        if (other.hasRoutingTable()) {
          mergeRoutingTable(other.getRoutingTable());
        }
        if (other.hasRouteDownInformation()) {
          setRouteDownInformation(other.getRouteDownInformation());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasRoutingTable()) {
          
          return false;
        }
        if (!getRoutingTable().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              jadex.android.bluetooth.message.MessageProtos.RoutingType value = jadex.android.bluetooth.message.MessageProtos.RoutingType.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              fromAddress_ = input.readBytes();
              break;
            }
            case 26: {
              jadex.android.bluetooth.message.MessageProtos.RoutingTable.Builder subBuilder = jadex.android.bluetooth.message.MessageProtos.RoutingTable.newBuilder();
              if (hasRoutingTable()) {
                subBuilder.mergeFrom(getRoutingTable());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setRoutingTable(subBuilder.buildPartial());
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              routeDownInformation_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .jadex.android.bluetooth.message.RoutingType type = 1;
      private jadex.android.bluetooth.message.MessageProtos.RoutingType type_ = jadex.android.bluetooth.message.MessageProtos.RoutingType.Flooding;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public jadex.android.bluetooth.message.MessageProtos.RoutingType getType() {
        return type_;
      }
      public Builder setType(jadex.android.bluetooth.message.MessageProtos.RoutingType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = jadex.android.bluetooth.message.MessageProtos.RoutingType.Flooding;
        
        return this;
      }
      
      // optional string fromAddress = 2;
      private java.lang.Object fromAddress_ = "";
      public boolean hasFromAddress() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getFromAddress() {
        java.lang.Object ref = fromAddress_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          fromAddress_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFromAddress(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        fromAddress_ = value;
        
        return this;
      }
      public Builder clearFromAddress() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fromAddress_ = getDefaultInstance().getFromAddress();
        
        return this;
      }
      void setFromAddress(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        fromAddress_ = value;
        
      }
      
      // required .jadex.android.bluetooth.message.RoutingTable routingTable = 3;
      private jadex.android.bluetooth.message.MessageProtos.RoutingTable routingTable_ = jadex.android.bluetooth.message.MessageProtos.RoutingTable.getDefaultInstance();
      public boolean hasRoutingTable() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public jadex.android.bluetooth.message.MessageProtos.RoutingTable getRoutingTable() {
        return routingTable_;
      }
      public Builder setRoutingTable(jadex.android.bluetooth.message.MessageProtos.RoutingTable value) {
        if (value == null) {
          throw new NullPointerException();
        }
        routingTable_ = value;
        
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setRoutingTable(
          jadex.android.bluetooth.message.MessageProtos.RoutingTable.Builder builderForValue) {
        routingTable_ = builderForValue.build();
        
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeRoutingTable(jadex.android.bluetooth.message.MessageProtos.RoutingTable value) {
        if (((bitField0_ & 0x00000004) == 0x00000004) &&
            routingTable_ != jadex.android.bluetooth.message.MessageProtos.RoutingTable.getDefaultInstance()) {
          routingTable_ =
            jadex.android.bluetooth.message.MessageProtos.RoutingTable.newBuilder(routingTable_).mergeFrom(value).buildPartial();
        } else {
          routingTable_ = value;
        }
        
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearRoutingTable() {
        routingTable_ = jadex.android.bluetooth.message.MessageProtos.RoutingTable.getDefaultInstance();
        
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      // optional bool routeDownInformation = 4 [default = false];
      private boolean routeDownInformation_ ;
      public boolean hasRouteDownInformation() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public boolean getRouteDownInformation() {
        return routeDownInformation_;
      }
      public Builder setRouteDownInformation(boolean value) {
        bitField0_ |= 0x00000008;
        routeDownInformation_ = value;
        
        return this;
      }
      public Builder clearRouteDownInformation() {
        bitField0_ = (bitField0_ & ~0x00000008);
        routeDownInformation_ = false;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:jadex.android.bluetooth.message.RoutingInformation)
    }
    
    static {
      defaultInstance = new RoutingInformation(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:jadex.android.bluetooth.message.RoutingInformation)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
