# build properties
# branchToBuild
# tagToBuild
# performanceTests
# publishArtifacts
# publishToDummy
# publishCommercial
# deployDists
# resetPatchVersion
# tagBuild
# deployDevSchema
# gradlew -Pdist=publishdists publish -x test -PpublishArtifacts -Prepouser=deployment -Prepopassword= -Production -Psigning.secretKeyRingFile=master.key 

image: openjdk:11-jdk

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  
  # default tasks for all branches
  BUILD: "true"
  TEST: "true"
  
  # additional default tasks for master and stable
  QUALITY: "unset"
  DEPLOYZIPS: "unset"
  DEPLOYDOCS: "unset"
  UPLOAD_ACTORON: "unset"
  TAG: "unset"
  
  # additional default tasks for stable only
  UPLOAD_CENTRAL: "unset"
  
stages:
  - build
  - testandquality
  - package
  - deploy
  - failure
  - success

# todo: move code from jenkinsutil.groovy to gradle file and make it a task
before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle;
  - apt-get update -qq && apt-get install -y -qq libxrender1 libxtst6
  - export DISPLAY=xvfb:1
  - QUALITY="false"
  - echo "BUILD:" $BUILD
  - echo "QUALITY" $QUALITY
  - echo "TEST" $TEST
  - echo "JAVADOCZIP" $JAVADOCZIP
  - echo "DEPLOYDOCS" $DEPLOYDOCS
  - echo "DEPLOYZIPS" $DEPLOYZIPS
  - echo "UPLOAD" $UPLOAD

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

# **/build does not work correctly :-(
# https://gitlab.com/gitlab-org/gitlab-foss/issues/17850
build:
  stage: build
  script:
    - ./gradlew -Pdist=publishdists -Production clean build -x test -x javadoc
  allow_failure: false
  artifacts:
    paths:
      - "*/build"
      - "*/*/build"
      - "*/*/*/build"
      - "*/*/*/*/build"
    expire_in: 1 week
  rules:
    - if: '$BUILD == "true"'
      when: on_success
    
    
quality:
  stage: testandquality
  script:
    - ./gradlew -Production sonarqube -x test
  allow_failure: true
  rules:
    - if: $QUALITY=="true" || $QUALITY=="unset" && $CI_COMMIT_BRANCH=="master" || $QUALITY=="unset" &&  $CI_COMMIT_BRANCH=="stable"
      when: on_success

test:
  stage: testandquality
  # start xvfb server for running GUI tests
  services:
    - name: misoca/xvfb
      alias: xvfb
  script:
    - ./gradlew -Pdist=publishdists -Production :applications:micro:test :platform:base:test test -x javadoc
    #- ./gradlew -Pdist=publishdists -Production :tools:runtimetools-swing:test -x javadoc
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - "*/build/reports/tests/test"
      - "*/*/build/reports/tests/test"
      - "*/*/*/build/reports/tests/test"
      - "*/*/*/*/build/reports/tests/test"
    reports:
      junit: 
        - "*/build/test-results/test/*.xml"
        - "*/*/build/test-results/test/*.xml"
        - "*/*/*/build/test-results/test/*.xml"
        - "*/*/*/*/build/test-results/test/*.xml"
  rules:
    - if: '$TEST == "true"'
      when: on_success
 
# Build all kinds of docs/dist files as parallel as possible
# checkDists:
#  stage: package
#  script:
#    - ./gradlew -Pdist=publishdists -Production checkDists
    
# buildDocsPdf:
#  stage: package
#  script:
#    - ./gradlew -Production -b docs/mkdocs-ng/build.gradle buildDocsZip buildDocsPdf
    
javadocZip:
  stage: package
  script:
    - ./gradlew -Pdist=addonjavadoc -Production javadocZip
  rules:
    - if: $DEPLOYDOCS=="true" || $DEPLOYDOCS=="unset" && $CI_COMMIT_BRANCH=="master" ||  $DEPLOYDOCS=="unset" && $CI_COMMIT_BRANCH=="stable"
      when: on_success

# create artifacts to be uploaded to nexus
artifacts:
  stage: package
  script:
    - ./gradlew -Pdist=publishdists -Production jar sourcesJar javadocJar
  artifacts:
    paths:
      - "*/build/libs/*.jar"
      - "*/build/libs/*.jar.asc"
      - "*/*/build/libs/*.jar"
      - "*/*/build/libs/*.jar.asc"
      - "*/*/*/build/libs/*.jar"
      - "*/*/*/build/libs/*.jar.asc"
      - "*/*/*/*/build/libs/*.jar"
      - "*/*/*/*/build/libs/*.jar.asc"
    expire_in: 1 week
  rules:
    - if: $UPLOAD_ACTORON=="true" || $UPLOAD_ACTORON=="unset" && $CI_COMMIT_BRANCH=="master" ||  $UPLOAD_ACTORON=="unset" && $CI_COMMIT_BRANCH=="stable" || $UPLOAD_CENTRAL=="true" || $UPLOAD_CENTRAL=="unset" && $CI_COMMIT_BRANCH=="master" ||  $UPLOAD_CENTRAL=="unset" && $CI_COMMIT_BRANCH=="stable"
      when: on_success
      
deployZips:
  stage: deploy
  script:
    - ./gradlew -Pdist=publishdists -Production deployZips
  rules:
    - if: $DEPLOYZIPS=="true" || $DEPLOYZIPS=="unset" && $CI_COMMIT_BRANCH=="master" ||  $DEPLOYZIPS=="unset" && $CI_COMMIT_BRANCH=="stable"
      when: on_success

deployJavadocs:
  stage: deploy
  script:
    - ./gradlew -Production deployJavadocs
  rules:
    - if: $DEPLOYDOCS=="true" || $DEPLOYDOCS=="unset" && $CI_COMMIT_BRANCH=="master" ||  $DEPLOYDOCS=="unset" && $CI_COMMIT_BRANCH=="stable"
      when: on_success

deployArtifactsToActoron:
  stage: deploy
  script: 
    - ./gradlew -Pdist=publishdists -Production :environments:envsupport-jmonkey:publish publish -x test -P repo=actoron --info
  rules:
    - if: $UPLOAD_ACTORON=="true" || $UPLOAD_ACTORON=="unset" && $CI_COMMIT_BRANCH=="master" ||  $UPLOAD_ACTORON=="unset" && $CI_COMMIT_BRANCH=="stable"
      when: on_success
      
deployArtifactsToCentral:
  stage: deploy
  script: 
    - ./gradlew -Pdist=publishdists -Production :environments:envsupport-jmonkey:publish publish -x test -P repo=central --info
  rules:
    - if: $UPLOAD_CENTRAL=="true" || $UPLOAD_CENTRAL=="unset" && $CI_COMMIT_BRANCH=="master" || $UPLOAD_CENTRAL=="unset" &&  $CI_COMMIT_BRANCH=="stable"
      when: on_success
      
# cleanuprepo:    
#  stage: failure
#  script: 
#    - ./gradlew closeRepository
#  when: on_failure
#  only:
#    variables:
#      - $UPLOAD == "true"

# has some 401 error :-(  
#releaseStagingRepo:
#  stage: success
#  script:
#    -  ./gradlew closeAndReleaseRepository
#  only:
#    variables:
#      - $UPLOAD == "true"
    
updateTag:
  stage: success
  script:
    -  ./gradlew -Production updateTag
  rules:
    - if: $TAG=="true" || $CI_COMMIT_BRANCH=="master" && $TAG=="unset"
      when: on_success

# Rules for the whole workflow / pipeline
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'
      when: never
    - when: always