//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.02 at 11:26:54 AM CEST 
//


package sodekovs.bikesharing.data.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="stationID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="latitude" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="longitude" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="numberOfBikes" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="numberOfDocks" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Station")
public class Station {

    @XmlAttribute(name = "stationID", required = true)
    protected String stationID;
    @XmlAttribute(name = "latitude", required = true)
    protected double latitude;
    @XmlAttribute(name = "longitude", required = true)
    protected double longitude;
    @XmlAttribute(name = "numberOfBikes", required = true)
    protected int numberOfBikes;
    @XmlAttribute(name = "numberOfDocks", required = true)
    protected int numberOfDocks;

    /**
     * Gets the value of the stationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStationID() {
        return stationID;
    }

    /**
     * Sets the value of the stationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStationID(String value) {
        this.stationID = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     */
    public double getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     */
    public void setLatitude(double value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     */
    public double getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     */
    public void setLongitude(double value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the numberOfBikes property.
     * 
     */
    public int getNumberOfBikes() {
        return numberOfBikes;
    }

    /**
     * Sets the value of the numberOfBikes property.
     * 
     */
    public void setNumberOfBikes(int value) {
        this.numberOfBikes = value;
    }

    /**
     * Gets the value of the numberOfDocks property.
     * 
     */
    public int getNumberOfDocks() {
        return numberOfDocks;
    }

    /**
     * Sets the value of the numberOfDocks property.
     * 
     */
    public void setNumberOfDocks(int value) {
        this.numberOfDocks = value;
    }

}
