// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package jadex.android.bluetooth.domain;

public final class MessageProtos {
  private MessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface DeviceListOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // repeated string device = 1;
    java.util.List<String> getDeviceList();
    int getDeviceCount();
    String getDevice(int index);
  }
  public static final class DeviceList extends
      com.google.protobuf.GeneratedMessageLite
      implements DeviceListOrBuilder {
    // Use DeviceList.newBuilder() to construct.
    private DeviceList(Builder builder) {
      super(builder);
    }
    private DeviceList(boolean noInit) {}
    
    private static final DeviceList defaultInstance;
    public static DeviceList getDefaultInstance() {
      return defaultInstance;
    }
    
    public DeviceList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // repeated string device = 1;
    public static final int DEVICE_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList device_;
    public java.util.List<String>
        getDeviceList() {
      return device_;
    }
    public int getDeviceCount() {
      return device_.size();
    }
    public String getDevice(int index) {
      return device_.get(index);
    }
    
    private void initFields() {
      device_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < device_.size(); i++) {
        output.writeBytes(1, device_.getByteString(i));
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < device_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(device_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getDeviceList().size();
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static jadex.android.bluetooth.domain.MessageProtos.DeviceList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static jadex.android.bluetooth.domain.MessageProtos.DeviceList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static jadex.android.bluetooth.domain.MessageProtos.DeviceList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static jadex.android.bluetooth.domain.MessageProtos.DeviceList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static jadex.android.bluetooth.domain.MessageProtos.DeviceList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static jadex.android.bluetooth.domain.MessageProtos.DeviceList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static jadex.android.bluetooth.domain.MessageProtos.DeviceList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static jadex.android.bluetooth.domain.MessageProtos.DeviceList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static jadex.android.bluetooth.domain.MessageProtos.DeviceList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static jadex.android.bluetooth.domain.MessageProtos.DeviceList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(jadex.android.bluetooth.domain.MessageProtos.DeviceList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          jadex.android.bluetooth.domain.MessageProtos.DeviceList, Builder>
        implements jadex.android.bluetooth.domain.MessageProtos.DeviceListOrBuilder {
      // Construct using jadex.android.bluetooth.domain.MessageProtos.DeviceList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        device_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public jadex.android.bluetooth.domain.MessageProtos.DeviceList getDefaultInstanceForType() {
        return jadex.android.bluetooth.domain.MessageProtos.DeviceList.getDefaultInstance();
      }
      
      public jadex.android.bluetooth.domain.MessageProtos.DeviceList build() {
        jadex.android.bluetooth.domain.MessageProtos.DeviceList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private jadex.android.bluetooth.domain.MessageProtos.DeviceList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        jadex.android.bluetooth.domain.MessageProtos.DeviceList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public jadex.android.bluetooth.domain.MessageProtos.DeviceList buildPartial() {
        jadex.android.bluetooth.domain.MessageProtos.DeviceList result = new jadex.android.bluetooth.domain.MessageProtos.DeviceList(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          device_ = new com.google.protobuf.UnmodifiableLazyStringList(
              device_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.device_ = device_;
        return result;
      }
      
      public Builder mergeFrom(jadex.android.bluetooth.domain.MessageProtos.DeviceList other) {
        if (other == jadex.android.bluetooth.domain.MessageProtos.DeviceList.getDefaultInstance()) return this;
        if (!other.device_.isEmpty()) {
          if (device_.isEmpty()) {
            device_ = other.device_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDeviceIsMutable();
            device_.addAll(other.device_);
          }
          
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              ensureDeviceIsMutable();
              device_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated string device = 1;
      private com.google.protobuf.LazyStringList device_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDeviceIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          device_ = new com.google.protobuf.LazyStringArrayList(device_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<String>
          getDeviceList() {
        return java.util.Collections.unmodifiableList(device_);
      }
      public int getDeviceCount() {
        return device_.size();
      }
      public String getDevice(int index) {
        return device_.get(index);
      }
      public Builder setDevice(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDeviceIsMutable();
        device_.set(index, value);
        
        return this;
      }
      public Builder addDevice(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDeviceIsMutable();
        device_.add(value);
        
        return this;
      }
      public Builder addAllDevice(
          java.lang.Iterable<String> values) {
        ensureDeviceIsMutable();
        super.addAll(values, device_);
        
        return this;
      }
      public Builder clearDevice() {
        device_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        
        return this;
      }
      void addDevice(com.google.protobuf.ByteString value) {
        ensureDeviceIsMutable();
        device_.add(value);
        
      }
      
      // @@protoc_insertion_point(builder_scope:jadex.android.bluetooth.domain.DeviceList)
    }
    
    static {
      defaultInstance = new DeviceList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:jadex.android.bluetooth.domain.DeviceList)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
