/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jadex_bytecode_vmhacks_NativeHelper */

#ifndef _Included_jadex_bytecode_vmhacks_NativeHelper
#define _Included_jadex_bytecode_vmhacks_NativeHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jadex_bytecode_vmhacks_NativeHelper
 * Method:    setAccessible
 * Signature: (Ljava/lang/String;Ljava/lang/reflect/AccessibleObject;Z)V
 */
JNIEXPORT void JNICALL Java_jadex_bytecode_vmhacks_NativeHelper_setAccessible
  (JNIEnv *, jclass, jstring, jobject, jboolean);

/*
 * Class:     jadex_bytecode_vmhacks_NativeHelper
 * Method:    defineClass
 * Signature: (Ljava/lang/String;[BILjava/lang/ClassLoader;)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_jadex_bytecode_vmhacks_NativeHelper_defineClass
  (JNIEnv *, jclass, jstring, jbyteArray, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
