//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.23 at 01:45:23 PM MESZ 
//


package sodekovs.investigation.model;

import java.io.Serializable;
import java.util.ArrayList;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="start" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="end" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="step" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="values" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Configuration")
public class Configuration implements Serializable{

    /**
	 * 
	 */
	private static final long serialVersionUID = 5603963875857069542L;
	@XmlAttribute
    protected String name;
	@XmlAttribute
    protected String start;
    @XmlAttribute
    protected String end;
    @XmlAttribute
    protected String step;
    @XmlAttribute(name = "class")
    protected String clazz;
    @XmlAttribute
    protected String values; 
    @XmlAttribute
    protected String type;
   
    
    
	/**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	/**
     * Gets the value of the start property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public String getStart() {
        return start;
    }

    /**
     * Sets the value of the start property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStart(String value) {
        this.start = value;
    }

    /**
     * Gets the value of the end property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public String getEnd() {
        return end;
    }

    /**
     * Sets the value of the end property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEnd(String value) {
        this.end = value;
    }

    /**
     * Gets the value of the step property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public String getStep() {
        return step;
    }

    /**
     * Sets the value of the step property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStep(String value) {
        this.step = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the values property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValues() {
        return values;
    }

    /**
     * Sets the value of the values property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValues(String value) {
        this.values = value;
    }
    
    private ArrayList<String> valuesAsList;

    /**
   	 * Returns the values, initially "only" a string of values, as an Arraylist of separated values.
   	 * @return
   	 */
   	public ArrayList<String> getValuesAsList() {
   		if(valuesAsList == null){
   			valuesAsList = new ArrayList<String>();
   			String tmpValues = this.values;
   			
   			while(tmpValues.indexOf(";") != -1){
   				valuesAsList.add(tmpValues.substring(0, tmpValues.indexOf(";")));
   				tmpValues = tmpValues.substring(tmpValues.indexOf(";")+1);
   			}		
   		}
   		return this.valuesAsList;	
   	}
   	
    @XmlTransient
	private int parameterSweepCounter = 0;
	@XmlTransient
	private String currentValue = "0";

	  /**
	 * Needed, in case the parameter is swept to indicated current value.
	 * @return
	 */
	public int getParameterSweepCounter() {
		return parameterSweepCounter;
	}

	public void setParameterSweepCounter(int parameterSweepCounter) {
		this.parameterSweepCounter = parameterSweepCounter;
	}
	
	public void incrementParameterSweepCounter(){
		this.parameterSweepCounter++;
	}

	/**
	 * Denotes the current value of the parameter that is swept
	 * @return
	 */
	public String getCurrentValue() {
		return currentValue;
	}

	public void setCurrentValue(String currentValue) {
		this.currentValue = currentValue;
	}
	
	public boolean atEnd() {
		if(this.type.equalsIgnoreCase("space"))
		{
			if(this.getParameterSweepCounter() > ((Double.parseDouble(end) - Double.parseDouble(start)))/(Double.parseDouble(currentValue))+1)
				return true;
		}
		else if(this.type.equalsIgnoreCase("list"))
		{
			if(valuesAsList == null){
				this.getValuesAsList();
			}
			if(this.getParameterSweepCounter() > valuesAsList.size())
				return true;
			else
				return false;
		}
		else {
			System.err.println("Wrong configuration type");
		}
		return false;
		
	}

}
