//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.02 at 03:13:06 PM CEST 
//


package sodekovs.investigation.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}StartTime"/>
 *         &lt;element ref="{}TerminateCondition"/>
 *       &lt;/sequence>
 *       &lt;attribute name="rows" use="required" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="parallelRuns" use="required" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="delta" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "startTime",
    "terminateCondition"
})
@XmlRootElement(name = "General")
public class General {

    @XmlElement(name = "StartTime", required = true)
    protected StartTime startTime;
    @XmlElement(name = "TerminateCondition", required = true)
    protected TerminateCondition terminateCondition;
    @XmlAttribute(name = "rows", required = true)
    protected byte rows;
    @XmlAttribute(name = "parallelRuns", required = true)
    protected byte parallelRuns;
    @XmlAttribute(name = "delta", required = true)
    protected boolean delta;

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link StartTime }
     *     
     */
    public StartTime getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link StartTime }
     *     
     */
    public void setStartTime(StartTime value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the terminateCondition property.
     * 
     * @return
     *     possible object is
     *     {@link TerminateCondition }
     *     
     */
    public TerminateCondition getTerminateCondition() {
        return terminateCondition;
    }

    /**
     * Sets the value of the terminateCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link TerminateCondition }
     *     
     */
    public void setTerminateCondition(TerminateCondition value) {
        this.terminateCondition = value;
    }

    /**
     * Gets the value of the rows property.
     * 
     */
    public byte getRows() {
        return rows;
    }

    /**
     * Sets the value of the rows property.
     * 
     */
    public void setRows(byte value) {
        this.rows = value;
    }

    /**
     * Gets the value of the parallelRuns property.
     * 
     */
    public byte getParallelRuns() {
        return parallelRuns;
    }

    /**
     * Sets the value of the parallelRuns property.
     * 
     */
    public void setParallelRuns(byte value) {
        this.parallelRuns = value;
    }

    /**
     * Gets the value of the delta property.
     * 
     */
    public boolean isDelta() {
        return delta;
    }

    /**
     * Sets the value of the delta property.
     * 
     */
    public void setDelta(boolean value) {
        this.delta = value;
    }

}
