//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.02 at 03:13:06 PM CEST 
//


package sodekovs.investigation.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TerminateCondition"/>
 *       &lt;/sequence>
 *       &lt;attribute name="experiments" use="required" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "terminateCondition"
})
@XmlRootElement(name = "Rows")
public class Rows {

    @XmlElement(name = "TerminateCondition", required = true)
    protected TerminateCondition terminateCondition;
    @XmlAttribute(name = "experiments", required = true)
    protected byte experiments;

    /**
     * Gets the value of the terminateCondition property.
     * 
     * @return
     *     possible object is
     *     {@link TerminateCondition }
     *     
     */
    public TerminateCondition getTerminateCondition() {
        return terminateCondition;
    }

    /**
     * Sets the value of the terminateCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link TerminateCondition }
     *     
     */
    public void setTerminateCondition(TerminateCondition value) {
        this.terminateCondition = value;
    }

    /**
     * Gets the value of the experiments property.
     * 
     */
    public byte getExperiments() {
        return experiments;
    }

    /**
     * Sets the value of the experiments property.
     * 
     */
    public void setExperiments(byte value) {
        this.experiments = value;
    }

}
