//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.15 at 02:26:20 PM MESZ 
//


package sodekovs.investigation.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SourceSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SourceSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="$object.money"/>
 *     &lt;enumeration value="$object.ore"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SourceSimpleType")
@XmlEnum
public enum SourceSimpleType {

    @XmlEnumValue("$object.money")
    $_OBJECT_MONEY("$object.money"),
    @XmlEnumValue("$object.ore")
    $_OBJECT_ORE("$object.ore");
    private final String value;

    SourceSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SourceSimpleType fromValue(String v) {
        for (SourceSimpleType c: SourceSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
