//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.02 at 03:13:06 PM CEST 
//


package sodekovs.investigation.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}TerminationTime"/>
 *         &lt;element ref="{}SemanticCondition"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "terminationTime",
    "semanticCondition"
})
@XmlRootElement(name = "TerminateCondition")
public class TerminateCondition {

    @XmlElement(name = "TerminationTime")
    protected TerminationTime terminationTime;
    @XmlElement(name = "SemanticCondition")
    protected SemanticCondition semanticCondition;

    /**
     * Gets the value of the terminationTime property.
     * 
     * @return
     *     possible object is
     *     {@link TerminationTime }
     *     
     */
    public TerminationTime getTerminationTime() {
        return terminationTime;
    }

    /**
     * Sets the value of the terminationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link TerminationTime }
     *     
     */
    public void setTerminationTime(TerminationTime value) {
        this.terminationTime = value;
    }

    /**
     * Gets the value of the semanticCondition property.
     * 
     * @return
     *     possible object is
     *     {@link SemanticCondition }
     *     
     */
    public SemanticCondition getSemanticCondition() {
        return semanticCondition;
    }

    /**
     * Sets the value of the semanticCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link SemanticCondition }
     *     
     */
    public void setSemanticCondition(SemanticCondition value) {
        this.semanticCondition = value;
    }

}
