//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.23 at 01:45:23 PM MESZ 
//


package sodekovs.investigation.model;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Time"/>
 *         &lt;element ref="{}TargetFunction" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "time",
    "targetFunction"
})
@XmlRootElement(name = "TerminateCondition")
public class TerminateCondition implements Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = -147872002541135532L;
	@XmlElement(name = "Time", required = true)
    protected Time time;
    @XmlElement(name = "TargetFunction")
    protected TargetFunction targetFunction;

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link Time }
     *     
     */
    public Time getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link Time }
     *     
     */
    public void setTime(Time value) {
        this.time = value;
    }

    /**
     * Gets the value of the targetFunction property.
     * 
     * @return
     *     possible object is
     *     {@link TargetFunction }
     *     
     */
    public TargetFunction getTargetFunction() {
        return targetFunction;
    }

    /**
     * Sets the value of the targetFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetFunction }
     *     
     */
    public void setTargetFunction(TargetFunction value) {
        this.targetFunction = value;
    }

}
