package jadex.adapter.base.contextservice;

import jadex.adapter.base.IContext;
import jadex.adapter.base.IContextService;
import jadex.adapter.base.fipa.IAMS;
import jadex.bridge.IAgentIdentifier;
import jadex.commons.SUtil;
import jadex.commons.concurrent.IResultListener;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

/**
 *  Contexts are an abstract grouping mechanism for agents on a platform,
 *  which is managed using the context service.
 */
public class ContextService	implements IContextService
{
	//-------- attributes --------
	
	/** All contexts on the platform (name->context). */
	protected Map	contexts;
	
	/** The context counter for generating unique names. */
	protected int	contextcnt;
	
	//-------- constructors --------
	
	/**
	 *  Create a new context service.
	 */
	public ContextService()
	{
		
	}
	
	//-------- IContextService interface --------
	
	/**
	 *  Get all contexts on the platform (if any).
	 */
	public synchronized IContext[]	getContexts()
	{
		return contexts==null ? null :
			(IContext[])contexts.values().toArray(new IContext[contexts.size()]);
	}

	/**
	 *  Get all contexts with a given type (if any).
	 */
	public synchronized IContext[]	getContexts(String type)
	{
		List	result	= null;
		if(contexts!=null)
		{
			for(Iterator it=contexts.values().iterator(); it.hasNext(); )
			{
				IContext	context	= (IContext) it.next();
				if(SUtil.equals(context.getType(), type))
				{
					if(result==null)
						result	= new ArrayList();
					result.add(context);
				}
			}
		}
		return result==null ? null :
			(IContext[])result.toArray(new IContext[result.size()]);
	}

	/**
	 *  Get all direct contexts of an agent (if any).
	 */
	public synchronized IContext[]	getContexts(IAgentIdentifier agent)
	{
		List	result	= null;
		if(contexts!=null)
		{
			for(Iterator it=contexts.values().iterator(); it.hasNext(); )
			{
				IContext	context	= (IContext) it.next();
				if(context.containsAgent(agent))
				{
					if(result==null)
						result	= new ArrayList();
					result.add(context);
				}
			}
		}
		return result==null ? null :
			(IContext[])result.toArray(new IContext[result.size()]);		
	}
	
	/**
	 *  Get a context with a given name.
	 */
	public synchronized IContext	getContext(String name)
	{
		return contexts!=null ? (IContext)contexts.get(name) : null;
	}

	/**
	 *  Create a context.
	 *  @param name	The name of the new context or null for autogenerated name.
	 *  @param type	The type of the new context (if any).
	 *  @param parent	The parent of the new context (if any).
	 */
	public synchronized IContext	createContext(String name, String type, IContext parent)
	{
		if(name!=null && contexts!=null && contexts.containsKey(name))
			throw new RuntimeException("Context '"+name+"' already exists on the platform.");
		
		if(contexts==null)
			contexts	= new HashMap();
		
		if(name==null)
		{
			do
			{
				name	= (type!=null ? type : "context") + "_" + (++contextcnt); 
			}
			while(contexts.containsKey(name));
		}
		
		Context	context	= new Context(name, type, parent);
		if(parent!=null)
			((Context)parent).addChild(context);
		
		return context;
	}
	
	/**
	 *  Delete a context.
	 *  @param listener Listener to be called, when the context is deleted
	 *    (e.g. after all contained agents have been terminated).
	 */
	public synchronized void	deleteContext(final IContext context, final IResultListener listener)
	{
		final IAgentIdentifier[]	agents	= context.getAgents();
		if(agents!=null && agents.length>0)
		{
			IResultListener	l2	= listener!=null ? new IResultListener()
			{
				int tokill	= agents.length;
				Exception	exception;
				public void resultAvailable(Object result)
				{
					result();
				}
				public void exceptionOccurred(Exception exception)
				{
					if(this.exception==null)	// Only return first exception.
						this.exception	= exception;
					result();
				}
				protected void	result()
				{
					tokill--;
					if(tokill==0)
					{
						if(exception!=null)
							listener.exceptionOccurred(exception);
						else
							listener.resultAvailable(context);
					}
				}
			} : null;
			IAMS	ams	= null;
			ams.destroyAgent(null, l2);
		}
		else
		{
			
		}
	}

	//-------- IPlatformService interface --------

	/**
	 *  Start the service.
	 */
	public void start()
	{
		// Nothing to do here.
	}
	
	/**
	 *  Shutdown the service.
	 *  @param listener The listener.
	 */
	public void shutdown(IResultListener listener)
	{
		// Todo: delete contexts and therefore agents before AMS gets shut down???
	}
}
