/* Generated By:JJTree: Do not edit this line. src\main\java\jadex\javaparser\javaccimpl\ParserImplTreeConstants.java */

package jadex.javaparser.javaccimpl;

public interface ParserImplTreeConstants
{
  public int JJTVOID = 0;
  public int JJTPARAMETERNODE = 1;
  public int JJTSELECTNODE = 2;
  public int JJTCONDITIONALNODE = 3;
  public int JJTBOOLEANNODE = 4;
  public int JJTMATHNODE = 5;
  public int JJTCOMPARENODE = 6;
  public int JJTCASTNODE = 7;
  public int JJTREFLECTNODE = 8;
  public int JJTSELECTIONNODE = 9;
  public int JJTCOLLECTIONNODE = 10;
  public int JJTCONSTANTNODE = 11;
  public int JJTARGUMENTSNODE = 12;
  public int JJTARRAYNODE = 13;
  public int JJTTYPENODE = 14;


  public String[] jjtNodeName = {
    "void",
    "ParameterNode",
    "SelectNode",
    "ConditionalNode",
    "BooleanNode",
    "MathNode",
    "CompareNode",
    "CastNode",
    "ReflectNode",
    "SelectionNode",
    "CollectionNode",
    "ConstantNode",
    "ArgumentsNode",
    "ArrayNode",
    "TypeNode",
  };
}
