/* Generated By:JJTree&JavaCC: Do not edit this line. ParserImplConstants.java */
package jadex.javaparser.javaccimpl;

public interface ParserImplConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int MULTI_LINE_COMMENT = 7;
  int NEW = 8;
  int INSTANCEOF = 9;
  int SELECT = 10;
  int ALL = 11;
  int ANY = 12;
  int ONE = 13;
  int IOTA = 14;
  int FROM = 15;
  int IN = 16;
  int WHERE = 17;
  int ORDER = 18;
  int BY = 19;
  int ASC = 20;
  int DESC = 21;
  int BOOLEAN = 22;
  int DOUBLE = 23;
  int FLOAT = 24;
  int LONG = 25;
  int INT = 26;
  int SHORT = 27;
  int BYTE = 28;
  int CHAR = 29;
  int TRUE = 30;
  int FALSE = 31;
  int NULL = 32;
  int INTEGER_LITERAL = 33;
  int DECIMAL_LITERAL = 34;
  int HEX_LITERAL = 35;
  int OCTAL_LITERAL = 36;
  int FLOATING_POINT_LITERAL = 37;
  int EXPONENT = 38;
  int CHARACTER_LITERAL = 39;
  int STRING_LITERAL = 40;
  int QUESTIONMARK = 41;
  int IDENTIFIER = 42;
  int LETTER = 43;
  int DIGIT = 44;
  int LPAREN = 45;
  int RPAREN = 46;
  int LBRACE = 47;
  int RBRACE = 48;
  int LBRACKET = 49;
  int RBRACKET = 50;
  int SEMICOLON = 51;
  int COMMA = 52;
  int DOT = 53;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"new\"",
    "\"instanceof\"",
    "\"select\"",
    "\"all\"",
    "\"any\"",
    "\"one\"",
    "\"iota\"",
    "\"from\"",
    "\"in\"",
    "\"where\"",
    "\"order\"",
    "\"by\"",
    "\"asc\"",
    "\"desc\"",
    "\"boolean\"",
    "\"double\"",
    "\"float\"",
    "\"long\"",
    "\"int\"",
    "\"short\"",
    "\"byte\"",
    "\"char\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"?\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"<<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"!\"",
    "\"~\"",
    "\"=\"",
  };

}
