//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.10 at 11:42:51 AM CEST 
//


package sodekovs.bikesharing.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DestinationProbabilities">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}DestinationProbability" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="departureProbability" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="stationID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "destinationProbabilities"
})
@XmlRootElement(name = "ProbabilitiesForStation")
public class ProbabilitiesForStation {

    @XmlElement(name = "DestinationProbabilities", required = true)
    protected ProbabilitiesForStation.DestinationProbabilities destinationProbabilities;
    @XmlAttribute(name = "departureProbability", required = true)
    protected double departureProbability;
    @XmlAttribute(name = "stationID", required = true)
    protected String stationID;

    /**
     * Gets the value of the destinationProbabilities property.
     * 
     * @return
     *     possible object is
     *     {@link ProbabilitiesForStation.DestinationProbabilities }
     *     
     */
    public ProbabilitiesForStation.DestinationProbabilities getDestinationProbabilities() {
        return destinationProbabilities;
    }

    /**
     * Sets the value of the destinationProbabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProbabilitiesForStation.DestinationProbabilities }
     *     
     */
    public void setDestinationProbabilities(ProbabilitiesForStation.DestinationProbabilities value) {
        this.destinationProbabilities = value;
    }

    /**
     * Gets the value of the departureProbability property.
     * 
     */
    public double getDepartureProbability() {
        return departureProbability;
    }

    /**
     * Sets the value of the departureProbability property.
     * 
     */
    public void setDepartureProbability(double value) {
        this.departureProbability = value;
    }

    /**
     * Gets the value of the stationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStationID() {
        return stationID;
    }

    /**
     * Sets the value of the stationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStationID(String value) {
        this.stationID = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}DestinationProbability" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "destinationProbability"
    })
    public static class DestinationProbabilities {

        @XmlElement(name = "DestinationProbability", required = true)
        protected List<DestinationProbability> destinationProbability;

        /**
         * Gets the value of the destinationProbability property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the destinationProbability property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDestinationProbability().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DestinationProbability }
         * 
         * 
         */
        public List<DestinationProbability> getDestinationProbability() {
            if (destinationProbability == null) {
                destinationProbability = new ArrayList<DestinationProbability>();
            }
            return this.destinationProbability;
        }

    }

}
