//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.10 at 11:42:51 AM CEST 
//


package sodekovs.bikesharing.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProbabilitiesForStations">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}ProbabilitiesForStation" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Stations">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}Station" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="startTime" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="offset" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="runTotal" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="runRelative" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "probabilitiesForStations",
    "stations"
})
@XmlRootElement(name = "TimeSlice")
public class TimeSlice {

    @XmlElement(name = "ProbabilitiesForStations", required = true)
    protected TimeSlice.ProbabilitiesForStations probabilitiesForStations;
    @XmlElement(name = "Stations", required = true)
    protected TimeSlice.Stations stations;
    @XmlAttribute(name = "startTime", required = true)
    protected long startTime;
    @XmlAttribute(name = "offset", required = true)
    protected int offset;
    @XmlAttribute(name = "runTotal")
    protected Integer runTotal;
    @XmlAttribute(name = "runRelative")
    protected Double runRelative;

    /**
     * Gets the value of the probabilitiesForStations property.
     * 
     * @return
     *     possible object is
     *     {@link TimeSlice.ProbabilitiesForStations }
     *     
     */
    public TimeSlice.ProbabilitiesForStations getProbabilitiesForStations() {
        return probabilitiesForStations;
    }

    /**
     * Sets the value of the probabilitiesForStations property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeSlice.ProbabilitiesForStations }
     *     
     */
    public void setProbabilitiesForStations(TimeSlice.ProbabilitiesForStations value) {
        this.probabilitiesForStations = value;
    }

    /**
     * Gets the value of the stations property.
     * 
     * @return
     *     possible object is
     *     {@link TimeSlice.Stations }
     *     
     */
    public TimeSlice.Stations getStations() {
        return stations;
    }

    /**
     * Sets the value of the stations property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeSlice.Stations }
     *     
     */
    public void setStations(TimeSlice.Stations value) {
        this.stations = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     */
    public long getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     */
    public void setStartTime(long value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the offset property.
     * 
     */
    public int getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     */
    public void setOffset(int value) {
        this.offset = value;
    }

    /**
     * Gets the value of the runTotal property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRunTotal() {
        return runTotal;
    }

    /**
     * Sets the value of the runTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRunTotal(Integer value) {
        this.runTotal = value;
    }

    /**
     * Gets the value of the runRelative property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getRunRelative() {
        return runRelative;
    }

    /**
     * Sets the value of the runRelative property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRunRelative(Double value) {
        this.runRelative = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}ProbabilitiesForStation" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "probabilitiesForStation"
    })
    public static class ProbabilitiesForStations {

        @XmlElement(name = "ProbabilitiesForStation", required = true)
        protected List<ProbabilitiesForStation> probabilitiesForStation;

        /**
         * Gets the value of the probabilitiesForStation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the probabilitiesForStation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProbabilitiesForStation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ProbabilitiesForStation }
         * 
         * 
         */
        public List<ProbabilitiesForStation> getProbabilitiesForStation() {
            if (probabilitiesForStation == null) {
                probabilitiesForStation = new ArrayList<ProbabilitiesForStation>();
            }
            return this.probabilitiesForStation;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}Station" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "station"
    })
    public static class Stations {

        @XmlElement(name = "Station", required = true)
        protected List<Station> station;

        /**
         * Gets the value of the station property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the station property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Station }
         * 
         * 
         */
        public List<Station> getStation() {
            if (station == null) {
                station = new ArrayList<Station>();
            }
            return this.station;
        }

    }

}
