/*
 * PlayerBeanInfo.java
 *
 * Generated by Protege plugin Beanynizer.
 * Changes will be lost!
 */

package jadex.bdi.examples.blackjack;


/**
 *  Java beaninfo class for concept Player of blackjack_beans ontology.
 */
public class PlayerBeanInfo extends java.beans.SimpleBeanInfo
{
	//-------- bean related methods --------

	/** The property descriptors, constructed on first access. */
	private java.beans.PropertyDescriptor[] pds = null;

	/**
	 *  Get the property descriptors.
	 *  @return The property descriptors.
	 */
	public java.beans.PropertyDescriptor[] getPropertyDescriptors() {
		if(pds==null) {
			try {
				pds = new java.beans.PropertyDescriptor[]{
					 new java.beans.PropertyDescriptor("colorvalue", Player.class, "getColorValue", "setColorValue")
					, new java.beans.PropertyDescriptor("name", Player.class, "getName", "setName")
					, new java.beans.PropertyDescriptor("strategyname", Player.class, "getStrategyName", "setStrategyName")
					, new java.beans.PropertyDescriptor("account", Player.class, "getAccount", "setAccount")
					, new java.beans.PropertyDescriptor("playingstate", Player.class, "getState", "setState")
					, new java.beans.IndexedPropertyDescriptor("cards", Player.class,
						"getCards", "setCards", "getCard", "setCard")
					, new java.beans.PropertyDescriptor("bet", Player.class, "getBet", "setBet")
					, new java.beans.PropertyDescriptor("cardCnt", Player.class, "getCardCnt", null)
				};
			}
			catch(Exception e) {
				e.printStackTrace();
			}
		}
		return pds;
	}
}
